<input <?php foreach($attributes as $name => $value): ?><?php echo $name;?>="<?php echo $value; ?>" <?php endforeach; ?>/>
<?php if(isset($hint) && $hint): ?>
<?php if(!$loaded): ?>
<?php echo jquery()->core(); ?>
<script type="text/javascript" src="/assets/jquery/field/hint.js"></script>
<link rel="stylesheet" type="text/css" href="/assets/jquery/field/hint.css" />
<?php endif; ?>
<script type="text/javascript">jQuery('input.eve-field-hint').not('.eve-field-loaded').addClass('eve-field-loaded').hint('<?php echo str_replace("'", "\\'", $hint); ?>');</script>
<?php endif; ?>